[package]
name = "synthesizer-io-spect"
version = "0.1.0"
authors = ["Raph Levien <raph.levien@gmail.com>"]
license = "Apache-2.0"
description = "A spectrum analysis module"

[dependencies]
rustfft = "2.1.0"

[dev-dependencies]
png = "0.12.0"
hound = "3.4.0"
